# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('web_key', models.CharField(default='iu2gth', max_length=6)),
                ('public', models.BooleanField(default=True)),
                ('htmlHead', models.TextField()),
                ('htmlBody', models.TextField()),
                ('css', models.TextField()),
                ('javascript', models.TextField()),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
