# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='web_key',
            field=models.CharField(default='qqplfd', max_length=6),
        ),
    ]
