# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170607_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='web_key',
            field=models.CharField(default='zjxtal', max_length=6, unique=True),
        ),
    ]
