# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170608_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='web_key',
            field=models.CharField(blank=True, default='jylsee', max_length=6, unique=True),
        ),
    ]
