# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20170611_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='web_key',
            field=models.CharField(blank=True, default='q3fsvq', max_length=6, unique=True),
        ),
    ]
