# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20170611_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='css',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='htmlBody',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='htmlHead',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='javascript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='web_key',
            field=models.CharField(blank=True, default='ynvorj', max_length=6, unique=True),
        ),
    ]
