# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20170611_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='web_key',
            field=models.CharField(default='uohbqo', max_length=6, unique=True),
        ),
    ]
