# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20170616_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='web_key',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
