# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0013_auto_20170920_1509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('user', 'web_key')]),
        ),
    ]
