# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20170920_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sample',
            field=models.BooleanField(default=False),
        ),
    ]
