# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20171012_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='pages.Tag'),
        ),
    ]
