# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20171012_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sample',
        ),
    ]
