# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_page_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sample',
            field=models.BooleanField(default=False),
        ),
    ]
