# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_page_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
