# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
