# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0023_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='web_key',
            new_name='webKey',
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('user', 'webKey')]),
        ),
    ]
