# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20171017_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='save_count',
            field=models.IntegerField(default=0),
        ),
    ]
