# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_page_save_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='pages', to='pages.Tag'),
        ),
    ]
