# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20171017_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='pages', to='pages.Tag'),
        ),
    ]
