# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(max_length=160),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('user', 'slug')]),
        ),
    ]
